version: '3.4'

services:
  passenger.api:
    image: ${DOCKER_REGISTRY-}passengerapi
    build:
      context: .
      dockerfile: src/Passenger.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
    environment:
      SA_PASSWORD: "<YourStrong@Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
