version: '3.4'

services:
  passenger.api:
    depends_on:
      - db
    image: przemyslawslowik/passenger.api
    ports:
      - "5000:80"
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
    environment:
      SA_PASSWORD: "<YourStrong@Passw0rd>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
